# FROM almalinux:8
# # CMD [ "ping", "google.com" ]# here it works ping yahoo.com at runtime 
# ENTRYPOINT [ "ping", "google.com" ] # here it wont ping yahoo.com at runtime 

# both combination 


FROM almalinux:8
CMD [ "google.com" ]
ENTRYPOINT [ "ping" ]